version: '1'
services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/sites/:/etc/nginx/sites-available
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  php-fpm:
    build: ./containers/php
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www
    depends_on:
      - postgress
    environment:
      DATABASE_URL: postgres://todoapp@postgress/todos

  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
#      - ./containers/postgres/user-data.txt/var/lib/data
      - ./containers/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./containers/postgres/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
