version: '1'
services:
  nginx:
    container_name: nginx
    image: nginx:1.11.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/sites/:/etc/nginx/sites-available
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    container_name: web
    build: ./containers/php
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://todoapp@postgress/todos

  database:
    container_name: database
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    volumes:
      - ./containers/database/data:/docker-entrypoint-initdb.d
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: root
