version: '1'
services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/sites/:/etc/nginx/sites-available
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: ./containers/php
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://todoapp@postgress/todos

  database:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./containers/database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: root
